### ISSUE TITLE
Add solutions to Codeforces Div2 Contests

### ISSUE THREAD

**Issue by neeraj3029** [neeraj3029/ChefServings#44]
- Create a directory for the contest
 - Add code with name/username of the author associated
- Star the repo if you find it helpful 🍷

**Comment by pranjanpr** [comment]
@neeraj3029 I am new to open source. Please tell me more about how many div 2 problems and solutions to be added. Thanks

**Comment by jineshparakh** [comment]
Hey!
I would like to contribute to this issue
Could you please let me know the number of contests/ problems that one needs to add?
Can you please assign this to me!

**Comment by Pranjal81** [comment]
#45 please consider this too

**Comment by princekalra** [comment]
i want to work  on this please assign it to me
